<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMkhpaew\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMkhpaew/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMkhpaew.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMkhpaew\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMkhpaew\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Mkhpaew',
    'container.build_id' => '1c5f57bd',
    'container.build_time' => 1541429803,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMkhpaew');
